window.SCRAPED_JOBS_FEED = [
  {
    "id": "live-ashby-linear-d3bc1ced-3ce4-4086-a050-555055dbb1ff",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Linear",
    "batch": "Series A/B",
    "title": "Senior / Staff Fullstack Engineer",
    "location": "Europe",
    "salaryRange": ",000 - ,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Linear to build state of the art systems in Product. Live scraped from Ashby.",
    "applyUrl": "https://jobs.ashbyhq.com/linear/d3bc1ced-3ce4-4086-a050-555055dbb1ff",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-linear-cd5ae036-0223-427a-b038-ba16ef9dcb32",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Linear",
    "batch": "Series A/B",
    "title": "Senior / Staff Fullstack Engineer",
    "location": "North America",
    "salaryRange": ",000 - ,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Linear to build state of the art systems in Product. Live scraped from Ashby.",
    "applyUrl": "https://jobs.ashbyhq.com/linear/cd5ae036-0223-427a-b038-ba16ef9dcb32",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-linear-069c4628-88d7-4e4d-b393-c996fc7f3076",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Linear",
    "batch": "Series A/B",
    "title": "Senior / Staff Product Engineer",
    "location": "Europe",
    "salaryRange": ",000 - ,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Linear to build state of the art systems in Product. Live scraped from Ashby.",
    "applyUrl": "https://jobs.ashbyhq.com/linear/069c4628-88d7-4e4d-b393-c996fc7f3076",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-linear-453f1ba0-a35e-4ed2-8215-1514e0a30b92",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Linear",
    "batch": "Series A/B",
    "title": "Account Executive, Growth",
    "location": "North America",
    "salaryRange": ",000 - ,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Linear to build state of the art systems in GTM. Live scraped from Ashby.",
    "applyUrl": "https://jobs.ashbyhq.com/linear/453f1ba0-a35e-4ed2-8215-1514e0a30b92",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-cursor-0ec39ed7-a5dc-4551-bb26-b7f4f9fb4a74",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Cursor (Anysphere)",
    "batch": "Series A/B",
    "title": "Software Engineer, Growth ",
    "location": "San Francisco",
    "salaryRange": ",000 - ,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Cursor (Anysphere) to build state of the art systems in Engineering. Live scraped from Ashby.",
    "applyUrl": "https://jobs.ashbyhq.com/cursor/0ec39ed7-a5dc-4551-bb26-b7f4f9fb4a74",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-cursor-6d576a09-f30d-4e5e-bb58-5d7ef56cb511",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Cursor (Anysphere)",
    "batch": "Series A/B",
    "title": "Software Engineer, Infrastructure",
    "location": "San Francisco",
    "salaryRange": ",000 - ,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Cursor (Anysphere) to build state of the art systems in Engineering. Live scraped from Ashby.",
    "applyUrl": "https://jobs.ashbyhq.com/cursor/6d576a09-f30d-4e5e-bb58-5d7ef56cb511",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-cursor-77bf35db-119c-4533-8187-1e8d5ae08c45",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Cursor (Anysphere)",
    "batch": "Series A/B",
    "title": "Software Engineer, Core Services",
    "location": "San Francisco",
    "salaryRange": ",000 - ,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Cursor (Anysphere) to build state of the art systems in Engineering. Live scraped from Ashby.",
    "applyUrl": "https://jobs.ashbyhq.com/cursor/77bf35db-119c-4533-8187-1e8d5ae08c45",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-cursor-e08262e8-c089-488d-9b59-9e21f7702b64",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Cursor (Anysphere)",
    "batch": "Series A/B",
    "title": "Software Engineer, Client Infrastructure",
    "location": "San Francisco",
    "salaryRange": ",000 - ,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Cursor (Anysphere) to build state of the art systems in Engineering. Live scraped from Ashby.",
    "applyUrl": "https://jobs.ashbyhq.com/cursor/e08262e8-c089-488d-9b59-9e21f7702b64",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-elevenlabs-a571b8e4-8176-4e31-aab6-2287ee810236",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "ElevenLabs",
    "batch": "Series A/B",
    "title": "Account Manager - India ",
    "location": "India",
    "salaryRange": ",000 - ,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join ElevenLabs to build state of the art systems in Revenue. Live scraped from Ashby.",
    "applyUrl": "https://jobs.ashbyhq.com/elevenlabs/a571b8e4-8176-4e31-aab6-2287ee810236",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-elevenlabs-275f43d0-b62d-401d-830c-7c1ac0e688aa",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "ElevenLabs",
    "batch": "Series A/B",
    "title": "Enterprise Solutions Engineer - North America",
    "location": "United States",
    "salaryRange": ",000 - ,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join ElevenLabs to build state of the art systems in Engineering & Product. Live scraped from Ashby.",
    "applyUrl": "https://jobs.ashbyhq.com/elevenlabs/275f43d0-b62d-401d-830c-7c1ac0e688aa",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-elevenlabs-ac7cc39a-a58b-4ef2-961a-ca16e060a361",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "ElevenLabs",
    "batch": "Series A/B",
    "title": "Account Executive - Japan",
    "location": "Japan",
    "salaryRange": ",000 - ,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join ElevenLabs to build state of the art systems in Revenue. Live scraped from Ashby.",
    "applyUrl": "https://jobs.ashbyhq.com/elevenlabs/ac7cc39a-a58b-4ef2-961a-ca16e060a361",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-elevenlabs-158034c9-eb7c-4348-a0b8-fa9e817b29f1",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "ElevenLabs",
    "batch": "Series A/B",
    "title": "Sales Development - United States",
    "location": "San Francisco",
    "salaryRange": ",000 - ,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join ElevenLabs to build state of the art systems in Revenue. Live scraped from Ashby.",
    "applyUrl": "https://jobs.ashbyhq.com/elevenlabs/158034c9-eb7c-4348-a0b8-fa9e817b29f1",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-decagon-67c794bd-e423-44b2-8b80-d7b759994cde",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Decagon",
    "batch": "Series A/B",
    "title": "Enterprise Account Executive ",
    "location": "San Francisco",
    "salaryRange": ",000 - ,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Decagon to build state of the art systems in Sales. Live scraped from Ashby.",
    "applyUrl": "https://jobs.ashbyhq.com/decagon/67c794bd-e423-44b2-8b80-d7b759994cde",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-decagon-ca69cd40-646d-44a8-a052-6f40294b123b",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Decagon",
    "batch": "Series A/B",
    "title": "Director of Sales, Enterprise",
    "location": "San Francisco",
    "salaryRange": ",000 - ,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Decagon to build state of the art systems in Sales. Live scraped from Ashby.",
    "applyUrl": "https://jobs.ashbyhq.com/decagon/ca69cd40-646d-44a8-a052-6f40294b123b",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-decagon-c1ac7d78-028b-451e-a10a-48c3c11308ea",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Decagon",
    "batch": "Series A/B",
    "title": "Senior Research Engineer",
    "location": "San Francisco",
    "salaryRange": ",000 - ,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Decagon to build state of the art systems in Engineering. Live scraped from Ashby.",
    "applyUrl": "https://jobs.ashbyhq.com/decagon/c1ac7d78-028b-451e-a10a-48c3c11308ea",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-decagon-dcf9b561-f2fb-422b-88a9-33ce76e96608",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Decagon",
    "batch": "Series A/B",
    "title": "Senior Agent Product Manager",
    "location": "San Francisco",
    "salaryRange": ",000 - ,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Decagon to build state of the art systems in Deployment Strategists. Live scraped from Ashby.",
    "applyUrl": "https://jobs.ashbyhq.com/decagon/dcf9b561-f2fb-422b-88a9-33ce76e96608",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-sierra-8152eaf6-012b-4154-95e2-7d6c52faba93",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Sierra",
    "batch": "Series A/B",
    "title": "Enterprise Sales Engineer",
    "location": "San Francisco, CA",
    "salaryRange": ",000 - ,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Sierra to build state of the art systems in Sales. Live scraped from Ashby.",
    "applyUrl": "https://jobs.ashbyhq.com/sierra/8152eaf6-012b-4154-95e2-7d6c52faba93",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-sierra-8da2071d-5e2f-43da-9bb1-2c7b30c078af",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Sierra",
    "batch": "Series A/B",
    "title": "High Growth Enterprise Account Executive",
    "location": "San Francisco, CA",
    "salaryRange": ",000 - ,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Sierra to build state of the art systems in Sales. Live scraped from Ashby.",
    "applyUrl": "https://jobs.ashbyhq.com/sierra/8da2071d-5e2f-43da-9bb1-2c7b30c078af",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-sierra-41e66706-b647-4ab1-8c7f-8f2975babba7",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Sierra",
    "batch": "Series A/B",
    "title": "Enterprise Sales Director - Majors",
    "location": "US - Remote",
    "salaryRange": ",000 - ,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Sierra to build state of the art systems in Sales. Live scraped from Ashby.",
    "applyUrl": "https://jobs.ashbyhq.com/sierra/41e66706-b647-4ab1-8c7f-8f2975babba7",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-sierra-d77487f9-bab3-44c6-be18-744e7125c8b3",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Sierra",
    "batch": "Series A/B",
    "title": "Software Engineer, Platform",
    "location": "San Francisco, CA",
    "salaryRange": ",000 - ,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Sierra to build state of the art systems in Engineering. Live scraped from Ashby.",
    "applyUrl": "https://jobs.ashbyhq.com/sierra/d77487f9-bab3-44c6-be18-744e7125c8b3",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-modal-9b33ebe7-e829-4f03-97ba-5c94dbd7daf6",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Modal",
    "batch": "Series A/B",
    "title": "Member of Technical Staff - Systems",
    "location": "New York",
    "salaryRange": ",000 - ,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Modal to build state of the art systems in Engineering. Live scraped from Ashby.",
    "applyUrl": "https://jobs.ashbyhq.com/modal/9b33ebe7-e829-4f03-97ba-5c94dbd7daf6",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-modal-9fadb51f-ce11-41b1-84d5-470e66cc8ee9",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Modal",
    "batch": "Series A/B",
    "title": "Forward Deployed Engineer - ML",
    "location": "New York",
    "salaryRange": ",000 - ,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Modal to build state of the art systems in Engineering. Live scraped from Ashby.",
    "applyUrl": "https://jobs.ashbyhq.com/modal/9fadb51f-ce11-41b1-84d5-470e66cc8ee9",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-modal-225b43d8-ef14-4082-b16e-005c74b42957",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Modal",
    "batch": "Series A/B",
    "title": "Business Operations Manager",
    "location": "New York",
    "salaryRange": ",000 - ,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Modal to build state of the art systems in G&A. Live scraped from Ashby.",
    "applyUrl": "https://jobs.ashbyhq.com/modal/225b43d8-ef14-4082-b16e-005c74b42957",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-modal-af17da5e-23ca-4802-854d-5f0546e1ed32",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Modal",
    "batch": "Series A/B",
    "title": "Member of Technical Staff - ML Performance",
    "location": "New York",
    "salaryRange": ",000 - ,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Modal to build state of the art systems in Engineering. Live scraped from Ashby.",
    "applyUrl": "https://jobs.ashbyhq.com/modal/af17da5e-23ca-4802-854d-5f0546e1ed32",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-anthropic-4461450008",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Anthropic",
    "batch": "Scaleup",
    "title": "Account Executive, AI Native",
    "location": "New York City, NY; San Francisco, CA | New York City, NY",
    "salaryRange": ",000 - ,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building critical infrastructure and AI models at Anthropic. Live scraped from official Greenhouse portal.",
    "applyUrl": "https://job-boards.greenhouse.io/anthropic/jobs/4461450008",
    "postedDate": "2026-08-21",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-anthropic-5391376008",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Anthropic",
    "batch": "Scaleup",
    "title": "Account Executive - DNB",
    "location": "Singapore",
    "salaryRange": ",000 - ,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building critical infrastructure and AI models at Anthropic. Live scraped from official Greenhouse portal.",
    "applyUrl": "https://job-boards.greenhouse.io/anthropic/jobs/5391376008",
    "postedDate": "2026-08-21",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-anthropic-5101378008",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Anthropic",
    "batch": "Scaleup",
    "title": "Account Executive, Public Sector",
    "location": "Sydney, Australia",
    "salaryRange": ",000 - ,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building critical infrastructure and AI models at Anthropic. Live scraped from official Greenhouse portal.",
    "applyUrl": "https://job-boards.greenhouse.io/anthropic/jobs/5101378008",
    "postedDate": "2026-08-21",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-anthropic-5391381008",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Anthropic",
    "batch": "Scaleup",
    "title": "Account Executive - Public Sector (ASEAN)",
    "location": "Singapore",
    "salaryRange": ",000 - ,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building critical infrastructure and AI models at Anthropic. Live scraped from official Greenhouse portal.",
    "applyUrl": "https://job-boards.greenhouse.io/anthropic/jobs/5391381008",
    "postedDate": "2026-08-21",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-figma-5364702004",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Figma",
    "batch": "Scaleup",
    "title": "Account Executive, Emerging Enterprise (Berlin, Germany)",
    "location": "Berlin, Germany",
    "salaryRange": ",000 - ,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building critical infrastructure and AI models at Figma. Live scraped from official Greenhouse portal.",
    "applyUrl": "https://boards.greenhouse.io/figma/jobs/5364702004?gh_jid=5364702004",
    "postedDate": "2026-07-22",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-figma-5426468004",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Figma",
    "batch": "Scaleup",
    "title": "Account Executive, Enterprise",
    "location": "San Francisco, CA • New York, NY • United States",
    "salaryRange": ",000 - ,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building critical infrastructure and AI models at Figma. Live scraped from official Greenhouse portal.",
    "applyUrl": "https://boards.greenhouse.io/figma/jobs/5426468004?gh_jid=5426468004",
    "postedDate": "2026-07-22",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-figma-5579204004",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Figma",
    "batch": "Scaleup",
    "title": "Account Executive, Enterprise (Bengaluru, India)",
    "location": "Bengaluru, India",
    "salaryRange": ",000 - ,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building critical infrastructure and AI models at Figma. Live scraped from official Greenhouse portal.",
    "applyUrl": "https://boards.greenhouse.io/figma/jobs/5579204004?gh_jid=5579204004",
    "postedDate": "2026-07-22",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-figma-5783812004",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Figma",
    "batch": "Scaleup",
    "title": "Account Executive, Enterprise (Berlin, Germany)",
    "location": "Berlin, Germany",
    "salaryRange": ",000 - ,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building critical infrastructure and AI models at Figma. Live scraped from official Greenhouse portal.",
    "applyUrl": "https://boards.greenhouse.io/figma/jobs/5783812004?gh_jid=5783812004",
    "postedDate": "2026-07-22",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-scaleai-4715970005",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Scale AI",
    "batch": "Scaleup",
    "title": "AI Advisory Consultant",
    "location": "San Francisco, CA; New York, NY",
    "salaryRange": ",000 - ,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building critical infrastructure and AI models at Scale AI. Live scraped from official Greenhouse portal.",
    "applyUrl": "https://job-boards.greenhouse.io/scaleai/jobs/4715970005",
    "postedDate": "2026-08-04",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-scaleai-4715976005",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Scale AI",
    "batch": "Scaleup",
    "title": "AI Advisory Principal",
    "location": "San Francisco, CA; New York, NY",
    "salaryRange": ",000 - ,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building critical infrastructure and AI models at Scale AI. Live scraped from official Greenhouse portal.",
    "applyUrl": "https://job-boards.greenhouse.io/scaleai/jobs/4715976005",
    "postedDate": "2026-08-04",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-scaleai-4654510005",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Scale AI",
    "batch": "Scaleup",
    "title": "AI Applications Ops Manager, GPS",
    "location": "Doha, Qatar ",
    "salaryRange": ",000 - ,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building critical infrastructure and AI models at Scale AI. Live scraped from official Greenhouse portal.",
    "applyUrl": "https://job-boards.greenhouse.io/scaleai/jobs/4654510005",
    "postedDate": "2026-08-19",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-scaleai-4703343005",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Scale AI",
    "batch": "Scaleup",
    "title": "AI Builder Intern",
    "location": "San Francisco, CA",
    "salaryRange": ",000 - ,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building critical infrastructure and AI models at Scale AI. Live scraped from official Greenhouse portal.",
    "applyUrl": "https://job-boards.greenhouse.io/scaleai/jobs/4703343005",
    "postedDate": "2026-08-11",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-discord-8599937002",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Discord",
    "batch": "Scaleup",
    "title": "Account Manager, Advertising Solutions",
    "location": "San Francisco Bay Area ",
    "salaryRange": ",000 - ,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building critical infrastructure and AI models at Discord. Live scraped from official Greenhouse portal.",
    "applyUrl": "https://job-boards.greenhouse.io/discord/jobs/8599937002",
    "postedDate": "2026-08-06",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-discord-8686353002",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Discord",
    "batch": "Scaleup",
    "title": "Advertising Operations Manager",
    "location": "San Francisco Bay Area or New York (Remote)",
    "salaryRange": ",000 - ,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building critical infrastructure and AI models at Discord. Live scraped from official Greenhouse portal.",
    "applyUrl": "https://job-boards.greenhouse.io/discord/jobs/8686353002",
    "postedDate": "2026-08-21",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-discord-8625545002",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Discord",
    "batch": "Scaleup",
    "title": "Associate Product Counsel, Safety",
    "location": "San Francisco Bay Area",
    "salaryRange": ",000 - ,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building critical infrastructure and AI models at Discord. Live scraped from official Greenhouse portal.",
    "applyUrl": "https://job-boards.greenhouse.io/discord/jobs/8625545002",
    "postedDate": "2026-07-31",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-discord-8680047002",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Discord",
    "batch": "Scaleup",
    "title": "Commercial Policy Lead, Brand Safety & Malware",
    "location": "San Francisco Bay Area ",
    "salaryRange": ",000 - ,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building critical infrastructure and AI models at Discord. Live scraped from official Greenhouse portal.",
    "applyUrl": "https://job-boards.greenhouse.io/discord/jobs/8680047002",
    "postedDate": "2026-08-05",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-coinbase-7822885",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Coinbase",
    "batch": "Scaleup",
    "title": "Accounting Manager, GL Operations & Intercompany",
    "location": "Remote - Canada",
    "salaryRange": ",000 - ,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building critical infrastructure and AI models at Coinbase. Live scraped from official Greenhouse portal.",
    "applyUrl": "https://www.coinbase.com/careers/positions/7822885?gh_jid=7822885",
    "postedDate": "2026-07-06",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-coinbase-8093264",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Coinbase",
    "batch": "Scaleup",
    "title": "Accounting Manager, GL Operations & Intercompany",
    "location": "Remote - USA",
    "salaryRange": ",000 - ,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building critical infrastructure and AI models at Coinbase. Live scraped from official Greenhouse portal.",
    "applyUrl": "https://www.coinbase.com/careers/positions/8093264?gh_jid=8093264",
    "postedDate": "2026-08-03",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-coinbase-7532645",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Coinbase",
    "batch": "Scaleup",
    "title": "Accounting Manager, Lending & Credit Products",
    "location": "Remote - USA",
    "salaryRange": ",000 - ,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building critical infrastructure and AI models at Coinbase. Live scraped from official Greenhouse portal.",
    "applyUrl": "https://www.coinbase.com/careers/positions/7532645?gh_jid=7532645",
    "postedDate": "2026-08-21",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-coinbase-7942306",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Coinbase",
    "batch": "Scaleup",
    "title": "AMLCO & Senior Compliance Associate",
    "location": "Remote - Cyprus",
    "salaryRange": ",000 - ,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building critical infrastructure and AI models at Coinbase. Live scraped from official Greenhouse portal.",
    "applyUrl": "https://www.coinbase.com/careers/positions/7942306?gh_jid=7942306",
    "postedDate": "2026-08-21",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-yc-raindrop",
    "source": "Y Combinator",
    "atsType": "ycombinator",
    "collectorId": "c_mt4s1dwc1n61l4s9i4",
    "company": "Raindrop",
    "batch": "W24",
    "title": "ML Engineer / LLM Autonomous Systems",
    "location": "San Francisco, CA / Remote",
    "salaryRange": ",000 - ,000",
    "equity": "0.5% - 2.0%",
    "techStack": [
      "Python",
      "PyTorch",
      "FastAPI",
      "PostgreSQL"
    ],
    "description": "Building next-generation intelligent agents for enterprise workflows. Backed by Y Combinator W24.",
    "applyUrl": "https://www.workatastartup.com/companies/raindrop",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-yc-coast",
    "source": "Y Combinator",
    "atsType": "ycombinator",
    "collectorId": "c_mt4s1dwc1n61l4s9i4",
    "company": "Coast",
    "batch": "S21",
    "title": "AI & Automation Software Engineer",
    "location": "New York, NY",
    "salaryRange": ",000 - ,000",
    "equity": "0.5% - 2.0%",
    "techStack": [
      "Python",
      "FastAPI",
      "PostgreSQL",
      "LangChain"
    ],
    "description": "Building financial automation infrastructure for commercial fleets and transportation logistics.",
    "applyUrl": "https://www.workatastartup.com/companies/coast",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-yc-athelas",
    "source": "Y Combinator",
    "atsType": "ycombinator",
    "collectorId": "c_mt4s1dwc1n61l4s9i4",
    "company": "Athelas",
    "batch": "S16",
    "title": "Senior AI Software Engineer - Clinical Ambient",
    "location": "Mountain View, CA / Remote",
    "salaryRange": ",000 - ,000",
    "equity": "0.5% - 2.0%",
    "techStack": [
      "React",
      "TypeScript",
      "Python",
      "PyTorch"
    ],
    "description": "Developing AI technology that automates clinical documentation and healthcare workflow orchestration.",
    "applyUrl": "https://www.workatastartup.com/companies/athelas",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-yc-voiceops",
    "source": "Y Combinator",
    "atsType": "ycombinator",
    "collectorId": "c_mt4s1dwc1n61l4s9i4",
    "company": "VoiceOps",
    "batch": "W17",
    "title": "Founding Speech & AI Systems Engineer",
    "location": "New York, NY / Remote",
    "salaryRange": ",000 - ,000",
    "equity": "0.5% - 2.0%",
    "techStack": [
      "Python",
      "PyTorch",
      "Audio Processing",
      "Whisper"
    ],
    "description": "Building real-time speech analytics and voice agent feedback systems for commercial revenue teams.",
    "applyUrl": "https://www.workatastartup.com/companies/voiceops",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-yc-method-financial",
    "source": "Y Combinator",
    "atsType": "ycombinator",
    "collectorId": "c_mt4s1dwc1n61l4s9i4",
    "company": "Method Financial",
    "batch": "W22",
    "title": "Senior Backend & Financial API Engineer",
    "location": "Austin, TX / Remote",
    "salaryRange": ",000 - ,000",
    "equity": "0.5% - 2.0%",
    "techStack": [
      "Go",
      "TypeScript",
      "PostgreSQL",
      "Kafka"
    ],
    "description": "Building real-time debt payment and liability data APIs for fintech developers and banks.",
    "applyUrl": "https://www.workatastartup.com/companies/method-financial",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-wellfound-2091105",
    "source": "Wellfound",
    "atsType": "wellfound",
    "collectorId": "c_wellfound_collector_3b1",
    "company": "TELUS Digital",
    "batch": "Series A",
    "title": "Content Reviewer - English US",
    "location": "USA",
    "salaryRange": "$14/hour",
    "equity": "0.1% - 0.5%",
    "techStack": [
      "android",
      "ios",
      "social media",
      "AI/ML"
    ],
    "description": "Our global AI Community is a vibrant network of more than one million contributors from\ndiverse backgrounds who help customers collect, enhance, train, translate, and localize\ncontent to build better ...",
    "applyUrl": "https://remotive.com/remote-jobs/all-others/content-reviewer-english-us-2091105",
    "postedDate": "2026-08-21",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-wellfound-2091098",
    "source": "Wellfound",
    "atsType": "wellfound",
    "collectorId": "c_wellfound_collector_3b1",
    "company": "Lemon.io",
    "batch": "Series A",
    "title": "Senior Golang Developer",
    "location": "Europe, USA, UK, Canada, Australia, Singapore",
    "salaryRange": ",000 - ,000",
    "equity": "0.1% - 0.5%",
    "techStack": [
      ".Net",
      "android",
      "C",
      "C#"
    ],
    "description": "Are you a talented Senior Developer looking for a remote job that lets you show your skills and get decent compensation? Look no further than Lemon.io — the marketplace that connects you with hand-pic...",
    "applyUrl": "https://remotive.com/remote-jobs/software-development/senior-golang-developer-2091098",
    "postedDate": "2026-08-20",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-wellfound-2091104",
    "source": "Wellfound",
    "atsType": "wellfound",
    "collectorId": "c_wellfound_collector_3b1",
    "company": "Shatterproof",
    "batch": "Series A",
    "title": "Vice President, Technology & Digital Strategy",
    "location": "USA",
    "salaryRange": "175k - 190k",
    "equity": "0.1% - 0.5%",
    "techStack": [
      "business intelligence",
      "cloud",
      "salesforce",
      "security"
    ],
    "description": "About ShatterproofShatterproof is a national nonprofit working toward a world where addiction never defines or ends a life. Through evidence-based programs, advocacy, and public education, Shatterproo...",
    "applyUrl": "https://remotive.com/remote-jobs/all-others/vice-president-technology-digital-strategy-2091104",
    "postedDate": "2026-08-20",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-wellfound-2091097",
    "source": "Wellfound",
    "atsType": "wellfound",
    "collectorId": "c_wellfound_collector_3b1",
    "company": "Lemon.io",
    "batch": "Series A",
    "title": "Senior Data Engineer",
    "location": "LATAM, Europe, USA, Canada, APAC",
    "salaryRange": ",000 - ,000",
    "equity": "0.1% - 0.5%",
    "techStack": [
      ".Net",
      "android",
      "apache",
      "AWS"
    ],
    "description": "Are you a talented Senior Data Engineer looking for a remote job that lets you show your skills and get decent compensation? Look no further than Lemon.io — the marketplace that connects you with hand...",
    "applyUrl": "https://remotive.com/remote-jobs/software-development/senior-data-engineer-2091097",
    "postedDate": "2026-08-19",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-wellfound-1919266",
    "source": "Wellfound",
    "atsType": "wellfound",
    "collectorId": "c_wellfound_collector_3b1",
    "company": "A.Team",
    "batch": "Series A",
    "title": "Senior Independent AI Engineer / Architect",
    "location": "Americas, Europe, Israel",
    "salaryRange": "$120 - $170 /hour",
    "equity": "0.1% - 0.5%",
    "techStack": [
      "go",
      "UI/UX",
      "wordpress",
      "chat"
    ],
    "description": "Senior Independent AI Engineer / Architect\nRemote | Americas, Europe, or Israel\n \nMost AI engineers can find work.\n \nFinding work worth doing is harder.\n \nA.Team is an invite-only network of senior AI...",
    "applyUrl": "https://remotive.com/remote-jobs/software-development/senior-independent-ai-engineer-architect-1919266",
    "postedDate": "2026-08-16",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-wellfound-1919265",
    "source": "Wellfound",
    "atsType": "wellfound",
    "collectorId": "c_wellfound_collector_3b1",
    "company": "A.Team",
    "batch": "Series A",
    "title": "Senior Independent Software Developer",
    "location": "Americas, Europe, Israel",
    "salaryRange": "$90 - $150 /hour",
    "equity": "0.1% - 0.5%",
    "techStack": [
      "go",
      "wordpress",
      "chat",
      "apple"
    ],
    "description": "You must be located in the Americas, Europe, or Israel to apply.A·Team is a VC-backed, stealth, application-only home on the internet for senior independent software builders to team up with hand-pick...",
    "applyUrl": "https://remotive.com/remote-jobs/software-development/senior-independent-software-developer-1919265",
    "postedDate": "2026-08-16",
    "healthStatus": "live_verified"
  }
];
