window.SCRAPED_JOBS_FEED = [
  {
    "id": "live-yc-raindrop",
    "source": "Y Combinator",
    "atsType": "ycombinator",
    "collectorId": "c_mt4s1dwc1n61l4s9i4",
    "company": "Raindrop",
    "batch": "W24",
    "title": "ML Engineer / LLM Autonomous Systems",
    "location": "San Francisco, CA / Remote",
    "salaryRange": "$160,000 - $240,000",
    "equity": "0.5% - 2.0%",
    "techStack": [
      "Python",
      "PyTorch",
      "FastAPI",
      "PostgreSQL"
    ],
    "description": "Building next-generation intelligent agents for enterprise workflows. Backed by Y Combinator W24.",
    "applyUrl": "https://www.workatastartup.com/companies/raindrop",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-yc-coast",
    "source": "Y Combinator",
    "atsType": "ycombinator",
    "collectorId": "c_mt4s1dwc1n61l4s9i4",
    "company": "Coast",
    "batch": "S21",
    "title": "AI & Automation Software Engineer",
    "location": "New York, NY",
    "salaryRange": "$160,000 - $240,000",
    "equity": "0.5% - 2.0%",
    "techStack": [
      "Python",
      "FastAPI",
      "PostgreSQL",
      "LangChain"
    ],
    "description": "Building financial automation infrastructure for commercial fleets and transportation logistics.",
    "applyUrl": "https://www.workatastartup.com/companies/coast",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-yc-athelas",
    "source": "Y Combinator",
    "atsType": "ycombinator",
    "collectorId": "c_mt4s1dwc1n61l4s9i4",
    "company": "Athelas",
    "batch": "S16",
    "title": "Senior AI Software Engineer - Clinical Ambient",
    "location": "Mountain View, CA / Remote",
    "salaryRange": "$160,000 - $240,000",
    "equity": "0.5% - 2.0%",
    "techStack": [
      "React",
      "TypeScript",
      "Python",
      "PyTorch"
    ],
    "description": "Developing AI technology that automates clinical documentation and healthcare workflow orchestration.",
    "applyUrl": "https://www.workatastartup.com/companies/athelas",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-yc-voiceops",
    "source": "Y Combinator",
    "atsType": "ycombinator",
    "collectorId": "c_mt4s1dwc1n61l4s9i4",
    "company": "VoiceOps",
    "batch": "W17",
    "title": "Founding Speech & AI Systems Engineer",
    "location": "New York, NY / Remote",
    "salaryRange": "$160,000 - $240,000",
    "equity": "0.5% - 2.0%",
    "techStack": [
      "Python",
      "PyTorch",
      "Audio Processing",
      "Whisper"
    ],
    "description": "Building real-time speech analytics and voice agent feedback systems for commercial revenue teams.",
    "applyUrl": "https://www.workatastartup.com/companies/voiceops",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-yc-method-financial",
    "source": "Y Combinator",
    "atsType": "ycombinator",
    "collectorId": "c_mt4s1dwc1n61l4s9i4",
    "company": "Method Financial",
    "batch": "W22",
    "title": "Senior Backend & Financial API Engineer",
    "location": "Austin, TX / Remote",
    "salaryRange": "$160,000 - $240,000",
    "equity": "0.5% - 2.0%",
    "techStack": [
      "Go",
      "TypeScript",
      "PostgreSQL",
      "Kafka"
    ],
    "description": "Building real-time debt payment and liability data APIs for fintech developers and banks.",
    "applyUrl": "https://www.workatastartup.com/companies/method-financial",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-yc-lineleap",
    "source": "Y Combinator",
    "atsType": "ycombinator",
    "collectorId": "c_mt4s1dwc1n61l4s9i4",
    "company": "LineLeap",
    "batch": "W19",
    "title": "Fullstack Mobile & Platform Engineer",
    "location": "Chicago, IL / Remote",
    "salaryRange": "$160,000 - $240,000",
    "equity": "0.5% - 2.0%",
    "techStack": [
      "React Native",
      "Node.js",
      "PostgreSQL",
      "AWS"
    ],
    "description": "Scaling digital ticketing, venue operations, and automated mobile ordering across premier entertainment destinations.",
    "applyUrl": "https://www.workatastartup.com/companies/lineleap",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-linear-d3bc1ced-3ce4-4086-a050-555055dbb1ff",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Linear",
    "batch": "Series A/B",
    "title": "Senior / Staff Fullstack Engineer",
    "location": "Europe",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Linear to build cutting-edge systems in Product. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/linear/d3bc1ced-3ce4-4086-a050-555055dbb1ff",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-linear-cd5ae036-0223-427a-b038-ba16ef9dcb32",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Linear",
    "batch": "Series A/B",
    "title": "Senior / Staff Fullstack Engineer",
    "location": "North America",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Linear to build cutting-edge systems in Product. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/linear/cd5ae036-0223-427a-b038-ba16ef9dcb32",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-linear-069c4628-88d7-4e4d-b393-c996fc7f3076",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Linear",
    "batch": "Series A/B",
    "title": "Senior / Staff Product Engineer",
    "location": "Europe",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Linear to build cutting-edge systems in Product. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/linear/069c4628-88d7-4e4d-b393-c996fc7f3076",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-linear-453f1ba0-a35e-4ed2-8215-1514e0a30b92",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Linear",
    "batch": "Series A/B",
    "title": "Account Executive, Growth",
    "location": "North America",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Linear to build cutting-edge systems in GTM. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/linear/453f1ba0-a35e-4ed2-8215-1514e0a30b92",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-linear-12f8f208-0b9c-4569-bb3d-41c8a197029e",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Linear",
    "batch": "Series A/B",
    "title": "Senior / Staff Product Engineer",
    "location": "North America",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Linear to build cutting-edge systems in Product. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/linear/12f8f208-0b9c-4569-bb3d-41c8a197029e",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-linear-0c7c2e26-0a98-42cf-a47c-9a3999fb513b",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Linear",
    "batch": "Series A/B",
    "title": "Product Engineer",
    "location": "North America",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Linear to build cutting-edge systems in Product. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/linear/0c7c2e26-0a98-42cf-a47c-9a3999fb513b",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-linear-b7669c4b-eeca-421d-ba9a-d90203f6fcb2",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Linear",
    "batch": "Series A/B",
    "title": "Product Manager",
    "location": "North America",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Linear to build cutting-edge systems in Product. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/linear/b7669c4b-eeca-421d-ba9a-d90203f6fcb2",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-linear-86abcce0-04b2-405c-9a8e-e0ca84813914",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Linear",
    "batch": "Series A/B",
    "title": "Product Manager",
    "location": "Europe",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Linear to build cutting-edge systems in Product. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/linear/86abcce0-04b2-405c-9a8e-e0ca84813914",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-linear-d062065e-05bb-42ce-a430-ec205695cc2e",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Linear",
    "batch": "Series A/B",
    "title": "Product Support Specialist, Pacific/Mountain Time",
    "location": "North America",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Linear to build cutting-edge systems in GTM. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/linear/d062065e-05bb-42ce-a430-ec205695cc2e",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-linear-c21af93e-210f-4969-8eaa-90fb16a5b720",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Linear",
    "batch": "Series A/B",
    "title": "Account Executive, Startups",
    "location": "North America",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Linear to build cutting-edge systems in GTM. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/linear/c21af93e-210f-4969-8eaa-90fb16a5b720",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-cursor-0ec39ed7-a5dc-4551-bb26-b7f4f9fb4a74",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Cursor (Anysphere)",
    "batch": "Series A/B",
    "title": "Software Engineer, Growth ",
    "location": "San Francisco",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Cursor to build cutting-edge systems in Engineering. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/cursor/0ec39ed7-a5dc-4551-bb26-b7f4f9fb4a74",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-cursor-6d576a09-f30d-4e5e-bb58-5d7ef56cb511",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Cursor (Anysphere)",
    "batch": "Series A/B",
    "title": "Software Engineer, Infrastructure",
    "location": "San Francisco",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Cursor to build cutting-edge systems in Engineering. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/cursor/6d576a09-f30d-4e5e-bb58-5d7ef56cb511",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-cursor-77bf35db-119c-4533-8187-1e8d5ae08c45",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Cursor (Anysphere)",
    "batch": "Series A/B",
    "title": "Software Engineer, Core Services",
    "location": "San Francisco",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Cursor to build cutting-edge systems in Engineering. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/cursor/77bf35db-119c-4533-8187-1e8d5ae08c45",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-cursor-e08262e8-c089-488d-9b59-9e21f7702b64",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Cursor (Anysphere)",
    "batch": "Series A/B",
    "title": "Software Engineer, Client Infrastructure",
    "location": "San Francisco",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Cursor to build cutting-edge systems in Engineering. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/cursor/e08262e8-c089-488d-9b59-9e21f7702b64",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-cursor-36e69353-0452-4bf6-9f35-b1e7307959a7",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Cursor (Anysphere)",
    "batch": "Series A/B",
    "title": "Software Engineer, Generalist",
    "location": "San Francisco",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Cursor to build cutting-edge systems in Engineering. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/cursor/36e69353-0452-4bf6-9f35-b1e7307959a7",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-cursor-54a9cfcd-570a-4e9c-b52c-bd2336c60991",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Cursor (Anysphere)",
    "batch": "Series A/B",
    "title": "Software Engineer, Enterprise ",
    "location": "San Francisco",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Cursor to build cutting-edge systems in Engineering. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/cursor/54a9cfcd-570a-4e9c-b52c-bd2336c60991",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-cursor-0aa0650b-f93c-416e-9e2f-4fdf1556fd14",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Cursor (Anysphere)",
    "batch": "Series A/B",
    "title": "Software Engineer, ML Research ",
    "location": "San Francisco",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Cursor to build cutting-edge systems in Engineering. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/cursor/0aa0650b-f93c-416e-9e2f-4fdf1556fd14",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-cursor-3551cdaa-cf08-4c04-adbe-a968185bc769",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Cursor (Anysphere)",
    "batch": "Series A/B",
    "title": "Software Engineer, Product ",
    "location": "San Francisco",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Cursor to build cutting-edge systems in Engineering. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/cursor/3551cdaa-cf08-4c04-adbe-a968185bc769",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-cursor-61e4677d-cf3d-458a-bf6c-02287d5d2c39",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Cursor (Anysphere)",
    "batch": "Series A/B",
    "title": "Account Executive, Geo Enterprise - San Francisco",
    "location": "San Francisco",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Cursor to build cutting-edge systems in Sales. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/cursor/61e4677d-cf3d-458a-bf6c-02287d5d2c39",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-cursor-64a6cb18-493b-4d18-9f22-c661ae533bfa",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Cursor (Anysphere)",
    "batch": "Series A/B",
    "title": "Field Engineer",
    "location": "San Francisco",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Cursor to build cutting-edge systems in Solutions. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/cursor/64a6cb18-493b-4d18-9f22-c661ae533bfa",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  }
];