window.SCRAPED_JOBS_FEED = [
  {
    "id": "live-wf-2091105",
    "source": "Wellfound",
    "atsType": "wellfound",
    "collectorId": "c_wf_talent_41e9",
    "company": "TELUS Digital",
    "batch": "Series A/B",
    "title": "Content Reviewer - English US",
    "location": "USA",
    "salaryRange": "$14/hour",
    "equity": "0.1% - 0.75%",
    "techStack": [
      "android",
      "ios",
      "social media",
      "AI/ML"
    ],
    "description": "Our global AI Community is a vibrant network of more than one million contributors from\ndiverse backgrounds who help customers collect, enhance, train, translate, and localize\ncontent to build better AI models. Become pa...",
    "applyUrl": "https://remotive.com/remote-jobs/all-others/content-reviewer-english-us-2091105",
    "postedDate": "2026-08-21",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-wf-2091098",
    "source": "Wellfound",
    "atsType": "wellfound",
    "collectorId": "c_wf_talent_41e9",
    "company": "Lemon.io",
    "batch": "Series A/B",
    "title": "Senior Golang Developer",
    "location": "Europe, USA, UK, Canada, Australia, Singapore",
    "salaryRange": "$150,000 - $225,000",
    "equity": "0.1% - 0.75%",
    "techStack": [
      ".Net",
      "android",
      "C",
      "C#"
    ],
    "description": "Are you a talented Senior Developer looking for a remote job that lets you show your skills and get decent compensation? Look no further than Lemon.io — the marketplace that connects you with hand-picked startups in the ...",
    "applyUrl": "https://remotive.com/remote-jobs/software-development/senior-golang-developer-2091098",
    "postedDate": "2026-08-20",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-wf-2091104",
    "source": "Wellfound",
    "atsType": "wellfound",
    "collectorId": "c_wf_talent_41e9",
    "company": "Shatterproof",
    "batch": "Series A/B",
    "title": "Vice President, Technology & Digital Strategy",
    "location": "USA",
    "salaryRange": "$150,000 - $225,000",
    "equity": "0.1% - 0.75%",
    "techStack": [
      "business intelligence",
      "cloud",
      "salesforce",
      "security"
    ],
    "description": "About ShatterproofShatterproof is a national nonprofit working toward a world where addiction never defines or ends a life. Through evidence-based programs, advocacy, and public education, Shatterproof works to transform...",
    "applyUrl": "https://remotive.com/remote-jobs/all-others/vice-president-technology-digital-strategy-2091104",
    "postedDate": "2026-08-20",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-wf-2091097",
    "source": "Wellfound",
    "atsType": "wellfound",
    "collectorId": "c_wf_talent_41e9",
    "company": "Lemon.io",
    "batch": "Series A/B",
    "title": "Senior Data Engineer",
    "location": "LATAM, Europe, USA, Canada, APAC",
    "salaryRange": "$150,000 - $225,000",
    "equity": "0.1% - 0.75%",
    "techStack": [
      ".Net",
      "android",
      "apache",
      "AWS"
    ],
    "description": "Are you a talented Senior Data Engineer looking for a remote job that lets you show your skills and get decent compensation? Look no further than Lemon.io — the marketplace that connects you with hand-picked startups in ...",
    "applyUrl": "https://remotive.com/remote-jobs/software-development/senior-data-engineer-2091097",
    "postedDate": "2026-08-19",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-wf-1919266",
    "source": "Wellfound",
    "atsType": "wellfound",
    "collectorId": "c_wf_talent_41e9",
    "company": "A.Team",
    "batch": "Series A/B",
    "title": "Senior Independent AI Engineer / Architect",
    "location": "Americas, Europe, Israel",
    "salaryRange": "$120 - $170 /hour",
    "equity": "0.1% - 0.75%",
    "techStack": [
      "go",
      "UI/UX",
      "wordpress",
      "chat"
    ],
    "description": "Senior Independent AI Engineer / Architect\nRemote | Americas, Europe, or Israel\n \nMost AI engineers can find work.\n \nFinding work worth doing is harder.\n \nA.Team is an invite-only network of senior AI engineers, ML engin...",
    "applyUrl": "https://remotive.com/remote-jobs/software-development/senior-independent-ai-engineer-architect-1919266",
    "postedDate": "2026-08-16",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-wf-1919265",
    "source": "Wellfound",
    "atsType": "wellfound",
    "collectorId": "c_wf_talent_41e9",
    "company": "A.Team",
    "batch": "Series A/B",
    "title": "Senior Independent Software Developer",
    "location": "Americas, Europe, Israel",
    "salaryRange": "$90 - $150 /hour",
    "equity": "0.1% - 0.75%",
    "techStack": [
      "go",
      "wordpress",
      "chat",
      "apple"
    ],
    "description": "You must be located in the Americas, Europe, or Israel to apply.A·Team is a VC-backed, stealth, application-only home on the internet for senior independent software builders to team up with hand-picked, high-growth comp...",
    "applyUrl": "https://remotive.com/remote-jobs/software-development/senior-independent-software-developer-1919265",
    "postedDate": "2026-08-16",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-wf-2091068",
    "source": "Wellfound",
    "atsType": "wellfound",
    "collectorId": "c_wf_talent_41e9",
    "company": "garden3d",
    "batch": "Series A/B",
    "title": "Head of Marketing & Communications",
    "location": "Worldwide",
    "salaryRange": "$150k - $230k",
    "equity": "0.1% - 0.75%",
    "techStack": [
      "C",
      "video",
      "open source",
      "AI/ML"
    ],
    "description": "We are hiring a Head of Marketing &amp; Communications to tell the garden3d story across the internet, from wherever in the world you happen to be.\nMore details if you check our original job posting link\nAbout garden3d\nW...",
    "applyUrl": "https://remotive.com/remote-jobs/marketing/head-of-marketing-communications-2091068",
    "postedDate": "2026-08-15",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-wf-2069746",
    "source": "Wellfound",
    "atsType": "wellfound",
    "collectorId": "c_wf_talent_41e9",
    "company": "Mitre Media",
    "batch": "Series A/B",
    "title": "Tech Lead Full-Stack Rails Engineer",
    "location": "USA, Canada, USA timezones",
    "salaryRange": "$170k - $200k",
    "equity": "0.1% - 0.75%",
    "techStack": [
      "api",
      "CSS",
      "docker",
      "elasticsearch"
    ],
    "description": "About Mitre Media\nMitre Media is redefining FinTech with AI-driven tools that empower millions of investors. Our portfolio, including Dividend.com and MutualFunds.com, leverages LLMs to deliver novel data insights and vi...",
    "applyUrl": "https://remotive.com/remote-jobs/software-development/tech-lead-full-stack-rails-engineer-2069746",
    "postedDate": "2026-08-14",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-wf-2091093",
    "source": "Wellfound",
    "atsType": "wellfound",
    "collectorId": "c_wf_talent_41e9",
    "company": "TELUS Digital",
    "batch": "Series A/B",
    "title": "Face Deduplication Collection",
    "location": "USA",
    "salaryRange": "$150,000 - $225,000",
    "equity": "0.1% - 0.75%",
    "techStack": [
      "research"
    ],
    "description": "The project compensation rate is $0.55 USD per accepted image. The objective of this project is to collect a large and diverse dataset of current neutral selfies, head-pose captures, and historical facial images to suppo...",
    "applyUrl": "https://remotive.com/remote-jobs/all-others/face-deduplication-collection-2091093",
    "postedDate": "2026-08-13",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-wf-1680495",
    "source": "Wellfound",
    "atsType": "wellfound",
    "collectorId": "c_wf_talent_41e9",
    "company": "Coalition Technologies ",
    "batch": "Series A/B",
    "title": "Remote Office Assistant",
    "location": "Worldwide",
    "salaryRange": "$31,2k- $52k",
    "equity": "0.1% - 0.75%",
    "techStack": [
      "CSS",
      "excel",
      "frontend",
      "git"
    ],
    "description": "Coalition Technologies is seeking a reliable, detail-oriented, and highly organized Remote Office Assistant to support administrative, bookkeeping, billing, reporting, data entry, and internal operations tasks. This role...",
    "applyUrl": "https://remotive.com/remote-jobs/marketing/remote-office-assistant-1680495",
    "postedDate": "2026-08-11",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-wf-2086540",
    "source": "Wellfound",
    "atsType": "wellfound",
    "collectorId": "c_wf_talent_41e9",
    "company": "Credit Wellness, LLC",
    "batch": "Series A/B",
    "title": "Inside Sales Contractor",
    "location": "Worldwide",
    "salaryRange": "OTE $25k - $35k",
    "equity": "0.1% - 0.75%",
    "techStack": [
      "CRM",
      "google sheets",
      "financial services",
      "Inside Sales"
    ],
    "description": "About Us\nWe are a financial services start up focusing on helping to improve consumer credit profiles. We are currently seeking KPI driven sales representatives looking to earn up to 45K in their first year while working...",
    "applyUrl": "https://remotive.com/remote-jobs/sales/inside-sales-contractor-2086540",
    "postedDate": "2026-08-08",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-wf-2091045",
    "source": "Wellfound",
    "atsType": "wellfound",
    "collectorId": "c_wf_talent_41e9",
    "company": "Unio Digital",
    "batch": "Series A/B",
    "title": "Tier III Service Desk Engineer",
    "location": "Worldwide",
    "salaryRange": "$150,000 - $225,000",
    "equity": "0.1% - 0.75%",
    "techStack": [
      "azure",
      "cisco",
      "security",
      "video"
    ],
    "description": "Unió Digital is an Arizona-based managed service provider (MSP) delivering Managed IT Services, Low Voltage Cabling, Access Control, Video Surveillance, and Intrusion Services. We believe technology should be intuitive, ...",
    "applyUrl": "https://remotive.com/remote-jobs/information-technology/tier-iii-service-desk-engineer-2091045",
    "postedDate": "2026-08-07",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-wf-2091088",
    "source": "Wellfound",
    "atsType": "wellfound",
    "collectorId": "c_wf_talent_41e9",
    "company": "Creative Force ",
    "batch": "Series A/B",
    "title": "Sales Jedi",
    "location": "Europe",
    "salaryRange": "$150,000 - $225,000",
    "equity": "0.1% - 0.75%",
    "techStack": [
      "saas",
      "video",
      "SOLID",
      "chat"
    ],
    "description": "Great salary | Profit share | 100% remote |Work from anywhere in Europe | SaaS\n \nAwesome opportunity for a self-motivated and energetic people person to join our remote team and help sell our world-leading SaaS products,...",
    "applyUrl": "https://remotive.com/remote-jobs/sales/sales-jedi-2091088",
    "postedDate": "2026-08-05",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-wf-2091087",
    "source": "Wellfound",
    "atsType": "wellfound",
    "collectorId": "c_wf_talent_41e9",
    "company": "Creative Force",
    "batch": "Series A/B",
    "title": "SaaS Product Support Jedi",
    "location": "Europe, EMEA, UK, Germany, France, European timezones",
    "salaryRange": "$150,000 - $225,000",
    "equity": "0.1% - 0.75%",
    "techStack": [
      "api",
      "CSS",
      "go",
      "html"
    ],
    "description": "We’re on the hunt for a sharp, self-driven SaaS pro who’s as comfortable troubleshooting API and integrations as they are navigating human conversations.\nOur European client base is growing fast and we need someone who c...",
    "applyUrl": "https://remotive.com/remote-jobs/customer-service/saas-product-support-jedi-2091087",
    "postedDate": "2026-08-05",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-wf-1185979",
    "source": "Wellfound",
    "atsType": "wellfound",
    "collectorId": "c_wf_talent_41e9",
    "company": "IAPWE",
    "batch": "Series A/B",
    "title": "Freelance Writer",
    "location": "Worldwide",
    "salaryRange": "$50-$75 /hour",
    "equity": "0.1% - 0.75%",
    "techStack": [
      "REST"
    ],
    "description": "Our organization is seeking content writers to create articles and blog posts on a variety of topics.\n \nThe rate of pay is $20 per 100 words (this comes out to approximately $100 per article or $50 per hour).\n \nSome topi...",
    "applyUrl": "https://remotive.com/remote-jobs/writing/freelance-writer-1185979",
    "postedDate": "2026-08-04",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-wf-1749306",
    "source": "Wellfound",
    "atsType": "wellfound",
    "collectorId": "c_wf_talent_41e9",
    "company": "Coalition Technologies ",
    "batch": "Series A/B",
    "title": "Freelance Copywriter",
    "location": "Worldwide",
    "salaryRange": "$20k -$35k",
    "equity": "0.1% - 0.75%",
    "techStack": [
      "accounting",
      "excel",
      "research",
      "data analysis"
    ],
    "description": "CT Marketing Agency is seeking skilled Freelance Copywriters to write high-quality, SEO-driven content for eCommerce and lead generation websites. This is a freelance, project-based writing role.\n \nThe ideal candidate ha...",
    "applyUrl": "https://remotive.com/remote-jobs/writing/freelance-copywriter-1749306",
    "postedDate": "2026-08-02",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-wf-2091081",
    "source": "Wellfound",
    "atsType": "wellfound",
    "collectorId": "c_wf_talent_41e9",
    "company": "Lemon.io",
    "batch": "Series A/B",
    "title": "Senior Graphic Designer",
    "location": "Americas, Europe, Asia, Africa, Oceania",
    "salaryRange": "$150,000 - $225,000",
    "equity": "0.1% - 0.75%",
    "techStack": [
      ".Net",
      "android",
      "C",
      "C#"
    ],
    "description": "Are you a talented Senior Designer looking for a remote job that lets you show your skills and get decent compensation? Look no further than Lemon.io — the marketplace that connects you with hand-picked startups in the U...",
    "applyUrl": "https://remotive.com/remote-jobs/design/senior-graphic-designer-2091081",
    "postedDate": "2026-07-28",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-wf-2090903",
    "source": "Wellfound",
    "atsType": "wellfound",
    "collectorId": "c_wf_talent_41e9",
    "company": "Workada",
    "batch": "Series A/B",
    "title": "Data Labeling Specialists",
    "location": "USA",
    "salaryRange": "$17/hr",
    "equity": "0.1% - 0.75%",
    "techStack": [
      "research",
      "digital content",
      "spreadsheets"
    ],
    "description": "Who We AreWorkada creates high-quality labeled data for advanced technology systems. Our team reviews, organizes, categorizes, evaluates, and quality-checks digital content so those systems can better understand informat...",
    "applyUrl": "https://remotive.com/remote-jobs/data/data-labeling-specialists-2090903",
    "postedDate": "2026-07-26",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-wf-2091075",
    "source": "Wellfound",
    "atsType": "wellfound",
    "collectorId": "c_wf_talent_41e9",
    "company": "Outsite",
    "batch": "Series A/B",
    "title": "Business Development Representative",
    "location": "Northern America, Europe, UK, France, European timezones",
    "salaryRange": "$45,000 - $50,000",
    "equity": "0.1% - 0.75%",
    "techStack": [
      "AI/ML",
      "CRM",
      "business development",
      "account management"
    ],
    "description": "## About Outsite\n \nOutsite is a global coliving company for remote workers — hotel-quality service, extended-stay flexibility, and a built-in community, at the intersection of hospitality and lifestyle. We operate 40+ pr...",
    "applyUrl": "https://remotive.com/remote-jobs/sales/business-development-representative-2091075",
    "postedDate": "2026-07-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-wf-2091074",
    "source": "Wellfound",
    "atsType": "wellfound",
    "collectorId": "c_wf_talent_41e9",
    "company": "TELUS Digital",
    "batch": "Series A/B",
    "title": "Content Reviewer - United States",
    "location": "USA",
    "salaryRange": "$14/hr",
    "equity": "0.1% - 0.75%",
    "techStack": [
      "android",
      "ios",
      "social media",
      "AI/ML"
    ],
    "description": " \nWe are looking for an independent, flexible, remote opportunity where you can help improve AI-powered search technology from the comfort of your home? If you're curious, internet-savvy, and enjoy evaluating online cont...",
    "applyUrl": "https://remotive.com/remote-jobs/all-others/content-reviewer-united-states-2091074",
    "postedDate": "2026-07-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-figma-5364702004",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Figma",
    "batch": "Scaleup",
    "title": "Account Executive, Emerging Enterprise (Berlin, Germany)",
    "location": "Berlin, Germany",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Figma. Live scraped from official Greenhouse board.",
    "applyUrl": "https://boards.greenhouse.io/figma/jobs/5364702004?gh_jid=5364702004",
    "postedDate": "2026-07-22",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-figma-5426468004",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Figma",
    "batch": "Scaleup",
    "title": "Account Executive, Enterprise",
    "location": "San Francisco, CA • New York, NY • United States",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Figma. Live scraped from official Greenhouse board.",
    "applyUrl": "https://boards.greenhouse.io/figma/jobs/5426468004?gh_jid=5426468004",
    "postedDate": "2026-07-22",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-figma-5579204004",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Figma",
    "batch": "Scaleup",
    "title": "Account Executive, Enterprise (Bengaluru, India)",
    "location": "Bengaluru, India",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Figma. Live scraped from official Greenhouse board.",
    "applyUrl": "https://boards.greenhouse.io/figma/jobs/5579204004?gh_jid=5579204004",
    "postedDate": "2026-07-22",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-figma-5783812004",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Figma",
    "batch": "Scaleup",
    "title": "Account Executive, Enterprise (Berlin, Germany)",
    "location": "Berlin, Germany",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Figma. Live scraped from official Greenhouse board.",
    "applyUrl": "https://boards.greenhouse.io/figma/jobs/5783812004?gh_jid=5783812004",
    "postedDate": "2026-07-22",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-figma-5428656004",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Figma",
    "batch": "Scaleup",
    "title": "Account Executive, Enterprise (Paris, France) ",
    "location": "Paris, France",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Figma. Live scraped from official Greenhouse board.",
    "applyUrl": "https://boards.greenhouse.io/figma/jobs/5428656004?gh_jid=5428656004",
    "postedDate": "2026-07-22",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-figma-5753209004",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Figma",
    "batch": "Scaleup",
    "title": "Account Executive, Enterprise (Singapore)",
    "location": "Singapore",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Figma. Live scraped from official Greenhouse board.",
    "applyUrl": "https://boards.greenhouse.io/figma/jobs/5753209004?gh_jid=5753209004",
    "postedDate": "2026-07-22",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-coinbase-7822885",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Coinbase",
    "batch": "Scaleup",
    "title": "Accounting Manager, GL Operations & Intercompany",
    "location": "Remote - Canada",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Coinbase. Live scraped from official Greenhouse board.",
    "applyUrl": "https://www.coinbase.com/careers/positions/7822885?gh_jid=7822885",
    "postedDate": "2026-07-06",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-coinbase-8093264",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Coinbase",
    "batch": "Scaleup",
    "title": "Accounting Manager, GL Operations & Intercompany",
    "location": "Remote - USA",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Coinbase. Live scraped from official Greenhouse board.",
    "applyUrl": "https://www.coinbase.com/careers/positions/8093264?gh_jid=8093264",
    "postedDate": "2026-08-03",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-coinbase-7532645",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Coinbase",
    "batch": "Scaleup",
    "title": "Accounting Manager, Lending & Credit Products",
    "location": "Remote - USA",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Coinbase. Live scraped from official Greenhouse board.",
    "applyUrl": "https://www.coinbase.com/careers/positions/7532645?gh_jid=7532645",
    "postedDate": "2026-08-21",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-coinbase-7942306",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Coinbase",
    "batch": "Scaleup",
    "title": "AMLCO & Senior Compliance Associate",
    "location": "Remote - Cyprus",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Coinbase. Live scraped from official Greenhouse board.",
    "applyUrl": "https://www.coinbase.com/careers/positions/7942306?gh_jid=7942306",
    "postedDate": "2026-08-21",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-coinbase-7875558",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Coinbase",
    "batch": "Scaleup",
    "title": "Analyst, Business Controller",
    "location": "Remote - EMEA",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Coinbase. Live scraped from official Greenhouse board.",
    "applyUrl": "https://www.coinbase.com/careers/positions/7875558?gh_jid=7875558",
    "postedDate": "2026-07-13",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-coinbase-8080028",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Coinbase",
    "batch": "Scaleup",
    "title": "Associate Manager, Premium & Wealth",
    "location": "Hybrid - London, UK",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Coinbase. Live scraped from official Greenhouse board.",
    "applyUrl": "https://www.coinbase.com/careers/positions/8080028?gh_jid=8080028",
    "postedDate": "2026-07-22",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-anthropic-4461450008",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Anthropic",
    "batch": "Scaleup",
    "title": "Account Executive, AI Native",
    "location": "New York City, NY; San Francisco, CA | New York City, NY",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Anthropic. Live scraped from official Greenhouse board.",
    "applyUrl": "https://job-boards.greenhouse.io/anthropic/jobs/4461450008",
    "postedDate": "2026-08-21",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-anthropic-5391376008",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Anthropic",
    "batch": "Scaleup",
    "title": "Account Executive - DNB",
    "location": "Singapore",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Anthropic. Live scraped from official Greenhouse board.",
    "applyUrl": "https://job-boards.greenhouse.io/anthropic/jobs/5391376008",
    "postedDate": "2026-08-21",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-anthropic-5101378008",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Anthropic",
    "batch": "Scaleup",
    "title": "Account Executive, Public Sector",
    "location": "Sydney, Australia",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Anthropic. Live scraped from official Greenhouse board.",
    "applyUrl": "https://job-boards.greenhouse.io/anthropic/jobs/5101378008",
    "postedDate": "2026-08-21",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-anthropic-5391381008",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Anthropic",
    "batch": "Scaleup",
    "title": "Account Executive - Public Sector (ASEAN)",
    "location": "Singapore",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Anthropic. Live scraped from official Greenhouse board.",
    "applyUrl": "https://job-boards.greenhouse.io/anthropic/jobs/5391381008",
    "postedDate": "2026-08-21",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-anthropic-5357965008",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Anthropic",
    "batch": "Scaleup",
    "title": "Accounting Analytics & BI Engineer",
    "location": "San Francisco, CA",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Anthropic. Live scraped from official Greenhouse board.",
    "applyUrl": "https://job-boards.greenhouse.io/anthropic/jobs/5357965008",
    "postedDate": "2026-08-21",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-anthropic-5205545008",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Anthropic",
    "batch": "Scaleup",
    "title": "Accounting, Revenue Internal Controls",
    "location": "San Francisco, CA | Seattle, WA",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Anthropic. Live scraped from official Greenhouse board.",
    "applyUrl": "https://job-boards.greenhouse.io/anthropic/jobs/5205545008",
    "postedDate": "2026-08-21",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-modal-9b33ebe7-e829-4f03-97ba-5c94dbd7daf6",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Modal",
    "batch": "Series A/B",
    "title": "Member of Technical Staff - Systems",
    "location": "New York",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Modal to build state of the art systems in Engineering. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/modal/9b33ebe7-e829-4f03-97ba-5c94dbd7daf6",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-modal-9fadb51f-ce11-41b1-84d5-470e66cc8ee9",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Modal",
    "batch": "Series A/B",
    "title": "Forward Deployed Engineer - ML",
    "location": "New York",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Modal to build state of the art systems in Engineering. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/modal/9fadb51f-ce11-41b1-84d5-470e66cc8ee9",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-modal-225b43d8-ef14-4082-b16e-005c74b42957",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Modal",
    "batch": "Series A/B",
    "title": "Business Operations Manager",
    "location": "New York",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Modal to build state of the art systems in G&A. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/modal/225b43d8-ef14-4082-b16e-005c74b42957",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-modal-af17da5e-23ca-4802-854d-5f0546e1ed32",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Modal",
    "batch": "Series A/B",
    "title": "Member of Technical Staff - ML Performance",
    "location": "New York",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Modal to build state of the art systems in Engineering. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/modal/af17da5e-23ca-4802-854d-5f0546e1ed32",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-modal-265d6127-dd34-433b-819a-1f935572c7d8",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Modal",
    "batch": "Series A/B",
    "title": "Member of Technical Staff - Python SDK",
    "location": "New York",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Modal to build state of the art systems in Engineering. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/modal/265d6127-dd34-433b-819a-1f935572c7d8",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-modal-44b57790-528e-4f97-8613-03564316be8a",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Modal",
    "batch": "Series A/B",
    "title": "Customer Engineer",
    "location": "New York",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Modal to build state of the art systems in Engineering. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/modal/44b57790-528e-4f97-8613-03564316be8a",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-linear-d3bc1ced-3ce4-4086-a050-555055dbb1ff",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Linear",
    "batch": "Series A/B",
    "title": "Senior / Staff Fullstack Engineer",
    "location": "Europe",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Linear to build state of the art systems in Product. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/linear/d3bc1ced-3ce4-4086-a050-555055dbb1ff",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-linear-cd5ae036-0223-427a-b038-ba16ef9dcb32",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Linear",
    "batch": "Series A/B",
    "title": "Senior / Staff Fullstack Engineer",
    "location": "North America",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Linear to build state of the art systems in Product. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/linear/cd5ae036-0223-427a-b038-ba16ef9dcb32",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-linear-069c4628-88d7-4e4d-b393-c996fc7f3076",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Linear",
    "batch": "Series A/B",
    "title": "Senior / Staff Product Engineer",
    "location": "Europe",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Linear to build state of the art systems in Product. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/linear/069c4628-88d7-4e4d-b393-c996fc7f3076",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-linear-453f1ba0-a35e-4ed2-8215-1514e0a30b92",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Linear",
    "batch": "Series A/B",
    "title": "Account Executive, Growth",
    "location": "North America",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Linear to build state of the art systems in GTM. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/linear/453f1ba0-a35e-4ed2-8215-1514e0a30b92",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-linear-12f8f208-0b9c-4569-bb3d-41c8a197029e",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Linear",
    "batch": "Series A/B",
    "title": "Senior / Staff Product Engineer",
    "location": "North America",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Linear to build state of the art systems in Product. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/linear/12f8f208-0b9c-4569-bb3d-41c8a197029e",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-linear-0c7c2e26-0a98-42cf-a47c-9a3999fb513b",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Linear",
    "batch": "Series A/B",
    "title": "Product Engineer",
    "location": "North America",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Linear to build state of the art systems in Product. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/linear/0c7c2e26-0a98-42cf-a47c-9a3999fb513b",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-databricks-8559344002",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Databricks",
    "batch": "Scaleup",
    "title": "ソリューションアーキテクト (プリセールス)",
    "location": "Tokyo, Japan",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Databricks. Live scraped from official Greenhouse board.",
    "applyUrl": "https://databricks.com/company/careers/open-positions/job?gh_jid=8559344002",
    "postedDate": "2026-08-18",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-databricks-8428882002",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Databricks",
    "batch": "Scaleup",
    "title": "デリバリーソリューションアーキテクト",
    "location": "Tokyo, Japan",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Databricks. Live scraped from official Greenhouse board.",
    "applyUrl": "https://databricks.com/company/careers/open-positions/job?gh_jid=8428882002",
    "postedDate": "2026-08-18",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-databricks-6918763002",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Databricks",
    "batch": "Scaleup",
    "title": "Account Executive ",
    "location": "Bengaluru, India; Mumbai, India",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Databricks. Live scraped from official Greenhouse board.",
    "applyUrl": "https://databricks.com/company/careers/open-positions/job?gh_jid=6918763002",
    "postedDate": "2026-08-18",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-databricks-8441877002",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Databricks",
    "batch": "Scaleup",
    "title": "Account Executive - Federal",
    "location": "Australian Capital Territory, Australia",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Databricks. Live scraped from official Greenhouse board.",
    "applyUrl": "https://databricks.com/company/careers/open-positions/job?gh_jid=8441877002",
    "postedDate": "2026-08-19",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-databricks-7726495002",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Databricks",
    "batch": "Scaleup",
    "title": "Account Executive, Singapore",
    "location": "Singapore",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Databricks. Live scraped from official Greenhouse board.",
    "applyUrl": "https://databricks.com/company/careers/open-positions/job?gh_jid=7726495002",
    "postedDate": "2026-08-18",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-databricks-8604614002",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Databricks",
    "batch": "Scaleup",
    "title": "Accounting Manager",
    "location": "San Francisco, California",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Databricks. Live scraped from official Greenhouse board.",
    "applyUrl": "https://databricks.com/company/careers/open-positions/job?gh_jid=8604614002",
    "postedDate": "2026-08-18",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-decagon-67c794bd-e423-44b2-8b80-d7b759994cde",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Decagon",
    "batch": "Series A/B",
    "title": "Enterprise Account Executive ",
    "location": "San Francisco",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Decagon to build state of the art systems in Sales. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/decagon/67c794bd-e423-44b2-8b80-d7b759994cde",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-decagon-ca69cd40-646d-44a8-a052-6f40294b123b",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Decagon",
    "batch": "Series A/B",
    "title": "Director of Sales, Enterprise",
    "location": "San Francisco",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Decagon to build state of the art systems in Sales. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/decagon/ca69cd40-646d-44a8-a052-6f40294b123b",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-decagon-c1ac7d78-028b-451e-a10a-48c3c11308ea",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Decagon",
    "batch": "Series A/B",
    "title": "Senior Research Engineer",
    "location": "San Francisco",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Decagon to build state of the art systems in Engineering. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/decagon/c1ac7d78-028b-451e-a10a-48c3c11308ea",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-decagon-dcf9b561-f2fb-422b-88a9-33ce76e96608",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Decagon",
    "batch": "Series A/B",
    "title": "Senior Agent Product Manager",
    "location": "San Francisco",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Decagon to build state of the art systems in Deployment Strategists. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/decagon/dcf9b561-f2fb-422b-88a9-33ce76e96608",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-decagon-b295b323-3d01-4126-94c1-9fc7489ebdf0",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Decagon",
    "batch": "Series A/B",
    "title": "Engineering Manager, Agent Orchestration",
    "location": "San Francisco",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Decagon to build state of the art systems in Engineering. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/decagon/b295b323-3d01-4126-94c1-9fc7489ebdf0",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-decagon-f42e38fc-aa61-44c2-8e04-3e6d0ae5a7a3",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Decagon",
    "batch": "Series A/B",
    "title": "Strategic Account Director - West",
    "location": "Remote",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Decagon to build state of the art systems in Sales. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/decagon/f42e38fc-aa61-44c2-8e04-3e6d0ae5a7a3",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-elevenlabs-a571b8e4-8176-4e31-aab6-2287ee810236",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "ElevenLabs",
    "batch": "Series A/B",
    "title": "Account Manager - India ",
    "location": "India",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join ElevenLabs to build state of the art systems in Revenue. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/elevenlabs/a571b8e4-8176-4e31-aab6-2287ee810236",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-elevenlabs-275f43d0-b62d-401d-830c-7c1ac0e688aa",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "ElevenLabs",
    "batch": "Series A/B",
    "title": "Enterprise Solutions Engineer - North America",
    "location": "United States",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join ElevenLabs to build state of the art systems in Engineering & Product. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/elevenlabs/275f43d0-b62d-401d-830c-7c1ac0e688aa",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-elevenlabs-ac7cc39a-a58b-4ef2-961a-ca16e060a361",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "ElevenLabs",
    "batch": "Series A/B",
    "title": "Account Executive - Japan",
    "location": "Japan",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join ElevenLabs to build state of the art systems in Revenue. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/elevenlabs/ac7cc39a-a58b-4ef2-961a-ca16e060a361",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-elevenlabs-158034c9-eb7c-4348-a0b8-fa9e817b29f1",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "ElevenLabs",
    "batch": "Series A/B",
    "title": "Sales Development - United States",
    "location": "San Francisco",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join ElevenLabs to build state of the art systems in Revenue. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/elevenlabs/158034c9-eb7c-4348-a0b8-fa9e817b29f1",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-elevenlabs-c7d59014-b918-4c15-ae33-79f5c9f2cf9f",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "ElevenLabs",
    "batch": "Series A/B",
    "title": "Full-Stack Engineer (Back-End Leaning)",
    "location": "United Kingdom",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join ElevenLabs to build state of the art systems in Engineering & Product. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/elevenlabs/c7d59014-b918-4c15-ae33-79f5c9f2cf9f",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-elevenlabs-ada7cd2c-8b9f-4f19-a88b-7c2ca1be1fde",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "ElevenLabs",
    "batch": "Series A/B",
    "title": "Full-Stack Engineer (Front-End Leaning)",
    "location": "United Kingdom",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join ElevenLabs to build state of the art systems in Engineering & Product. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/elevenlabs/ada7cd2c-8b9f-4f19-a88b-7c2ca1be1fde",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-yc-hn-49393733",
    "source": "Y Combinator",
    "atsType": "ycombinator",
    "collectorId": "c_mt4s1dwc1n61l4s9i4",
    "company": "SalesPatriot (YC W25)",
    "batch": "YC Batch",
    "title": "Forward Deployed Engineers",
    "location": "San Francisco, CA / Remote",
    "salaryRange": "$160,000 - $240,000",
    "equity": "0.5% - 2.0%",
    "techStack": [
      "Python",
      "TypeScript",
      "React",
      "FastAPI",
      "AI/LLM"
    ],
    "description": "YC Startup role: SalesPatriot (YC W25) Is Hiring Forward Deployed Engineers. Live scraped via Bright Data Scraper Studio Collector c_mt4s1dwc1n61l4s9i4.",
    "applyUrl": "https://www.ycombinator.com/companies/salespatriot/jobs/M46X6YX-forward-deployed-engineer",
    "postedDate": "2026-08-21",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-yc-hn-49390910",
    "source": "Y Combinator",
    "atsType": "ycombinator",
    "collectorId": "c_mt4s1dwc1n61l4s9i4",
    "company": "LiteLLM (YC W23)",
    "batch": "YC Batch",
    "title": "– Rust / Performance Engineers",
    "location": "San Francisco, CA / Remote",
    "salaryRange": "$160,000 - $240,000",
    "equity": "0.5% - 2.0%",
    "techStack": [
      "Python",
      "TypeScript",
      "React",
      "FastAPI",
      "AI/LLM"
    ],
    "description": "YC Startup role: LiteLLM (YC W23) Is Hiring – Rust / Performance Engineers. Live scraped via Bright Data Scraper Studio Collector c_mt4s1dwc1n61l4s9i4.",
    "applyUrl": "https://jobs.ashbyhq.com/litellm/3f326076-7415-46a1-921e-8a1b1d6ee2b6",
    "postedDate": "2026-08-21",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-yc-hn-49319892",
    "source": "Y Combinator",
    "atsType": "ycombinator",
    "collectorId": "c_mt4s1dwc1n61l4s9i4",
    "company": "Tasklet (YC P26)",
    "batch": "YC Batch",
    "title": "a Head of Design Engineering",
    "location": "San Francisco, CA / Remote",
    "salaryRange": "$160,000 - $240,000",
    "equity": "0.5% - 2.0%",
    "techStack": [
      "Python",
      "TypeScript",
      "React",
      "FastAPI",
      "AI/LLM"
    ],
    "description": "YC Startup role: Tasklet (YC P26) Is Hiring a Head of Design Engineering. Live scraped via Bright Data Scraper Studio Collector c_mt4s1dwc1n61l4s9i4.",
    "applyUrl": "https://tasklet.ai/careers/head-of-design-engineering",
    "postedDate": "2026-08-16",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-yc-hn-49273395",
    "source": "Y Combinator",
    "atsType": "ycombinator",
    "collectorId": "c_mt4s1dwc1n61l4s9i4",
    "company": "GiveCampus (YC S15)",
    "batch": "YC Batch",
    "title": "Engineering Managers",
    "location": "San Francisco, CA / Remote",
    "salaryRange": "$160,000 - $240,000",
    "equity": "0.5% - 2.0%",
    "techStack": [
      "Python",
      "TypeScript",
      "React",
      "FastAPI",
      "AI/LLM"
    ],
    "description": "YC Startup role: GiveCampus (YC S15) Is Hiring Engineering Managers. Live scraped via Bright Data Scraper Studio Collector c_mt4s1dwc1n61l4s9i4.",
    "applyUrl": "https://job-boards.greenhouse.io/givecampus/jobs/4112793009",
    "postedDate": "2026-08-12",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-yc-hn-49165170",
    "source": "Y Combinator",
    "atsType": "ycombinator",
    "collectorId": "c_mt4s1dwc1n61l4s9i4",
    "company": "CollectWise (YC F24)",
    "batch": "YC Batch",
    "title": "CollectWise (YC F24) Is Hiring",
    "location": "San Francisco, CA / Remote",
    "salaryRange": "$160,000 - $240,000",
    "equity": "0.5% - 2.0%",
    "techStack": [
      "Python",
      "TypeScript",
      "React",
      "FastAPI",
      "AI/LLM"
    ],
    "description": "YC Startup role: CollectWise (YC F24) Is Hiring. Live scraped via Bright Data Scraper Studio Collector c_mt4s1dwc1n61l4s9i4.",
    "applyUrl": "https://www.ycombinator.com/companies/collectwise/jobs/oEAfzBS-ai-agent-engineer",
    "postedDate": "2026-08-04",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-yc-hn-49167444",
    "source": "Y Combinator",
    "atsType": "ycombinator",
    "collectorId": "c_mt4s1dwc1n61l4s9i4",
    "company": "Roame (YC S23)",
    "batch": "YC Batch",
    "title": "Lead Engineer",
    "location": "San Francisco, CA / Remote",
    "salaryRange": "$160,000 - $240,000",
    "equity": "0.5% - 2.0%",
    "techStack": [
      "Python",
      "TypeScript",
      "React",
      "FastAPI",
      "AI/LLM"
    ],
    "description": "YC Startup role: Roame (YC S23) Is Hiring Lead Engineer. Live scraped via Bright Data Scraper Studio Collector c_mt4s1dwc1n61l4s9i4.",
    "applyUrl": "https://www.ycombinator.com/companies/roame/jobs/mqqfa38-lead-full-stack-engineer",
    "postedDate": "2026-08-04",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-yc-hn-49319215",
    "source": "Y Combinator",
    "atsType": "ycombinator",
    "collectorId": "c_mt4s1dwc1n61l4s9i4",
    "company": "Gooseworks (YC W23)",
    "batch": "YC Batch",
    "title": "a Founding Builder / Engineer",
    "location": "San Francisco, CA / Remote",
    "salaryRange": "$160,000 - $240,000",
    "equity": "0.5% - 2.0%",
    "techStack": [
      "Python",
      "TypeScript",
      "React",
      "FastAPI",
      "AI/LLM"
    ],
    "description": "YC Startup role: Gooseworks (YC W23) Is Hiring a Founding Builder / Engineer. Live scraped via Bright Data Scraper Studio Collector c_mt4s1dwc1n61l4s9i4.",
    "applyUrl": "https://www.ycombinator.com/companies/gooseworks/jobs/UJ4vH2F-founding-engineer",
    "postedDate": "2026-08-16",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-yc-hn-49275465",
    "source": "Y Combinator",
    "atsType": "ycombinator",
    "collectorId": "c_mt4s1dwc1n61l4s9i4",
    "company": "Reflex (YC W23)",
    "batch": "YC Batch",
    "title": "Growth and GTM Roles",
    "location": "San Francisco, CA / Remote",
    "salaryRange": "$160,000 - $240,000",
    "equity": "0.5% - 2.0%",
    "techStack": [
      "Python",
      "TypeScript",
      "React",
      "FastAPI",
      "AI/LLM"
    ],
    "description": "YC Startup role: Reflex (YC W23) Is hiring Growth and GTM Roles. Live scraped via Bright Data Scraper Studio Collector c_mt4s1dwc1n61l4s9i4.",
    "applyUrl": "https://www.ycombinator.com/companies/reflex/jobs/71x5GFb-growth-engineer",
    "postedDate": "2026-08-12",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-yc-hn-49284697",
    "source": "Y Combinator",
    "atsType": "ycombinator",
    "collectorId": "c_mt4s1dwc1n61l4s9i4",
    "company": "ATG (YC F25)",
    "batch": "YC Batch",
    "title": "Member of Technical Staff (Data Platform)",
    "location": "San Francisco, CA / Remote",
    "salaryRange": "$160,000 - $240,000",
    "equity": "0.5% - 2.0%",
    "techStack": [
      "Python",
      "TypeScript",
      "React",
      "FastAPI",
      "AI/LLM"
    ],
    "description": "YC Startup role: ATG (YC F25) Is Hiring Member of Technical Staff (Data Platform). Live scraped via Bright Data Scraper Studio Collector c_mt4s1dwc1n61l4s9i4.",
    "applyUrl": "https://atg.science/careers",
    "postedDate": "2026-08-13",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-yc-hn-49143683",
    "source": "Y Combinator",
    "atsType": "ycombinator",
    "collectorId": "c_mt4s1dwc1n61l4s9i4",
    "company": "Great Question (YC W21)",
    "batch": "YC Batch",
    "title": "Senior Demand Gen Manager",
    "location": "San Francisco, CA / Remote",
    "salaryRange": "$160,000 - $240,000",
    "equity": "0.5% - 2.0%",
    "techStack": [
      "Python",
      "TypeScript",
      "React",
      "FastAPI",
      "AI/LLM"
    ],
    "description": "YC Startup role: Great Question (YC W21) Is Hiring Senior Demand Gen Manager. Live scraped via Bright Data Scraper Studio Collector c_mt4s1dwc1n61l4s9i4.",
    "applyUrl": "https://www.ycombinator.com/companies/great-question/jobs/YutDxyf-senior-demand-generation-manager",
    "postedDate": "2026-08-02",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-yc-hn-49139352",
    "source": "Y Combinator",
    "atsType": "ycombinator",
    "collectorId": "c_mt4s1dwc1n61l4s9i4",
    "company": "Morph (YC S23)",
    "batch": "YC Batch",
    "title": "Member of Technical Staff",
    "location": "San Francisco, CA / Remote",
    "salaryRange": "$160,000 - $240,000",
    "equity": "0.5% - 2.0%",
    "techStack": [
      "Python",
      "TypeScript",
      "React",
      "FastAPI",
      "AI/LLM"
    ],
    "description": "YC Startup role: Morph (YC S23) Is Hiring Member of Technical Staff. Live scraped via Bright Data Scraper Studio Collector c_mt4s1dwc1n61l4s9i4.",
    "applyUrl": "https://www.ycombinator.com/companies/morph/jobs/0Z8vI3K-member-of-technical-staff",
    "postedDate": "2026-08-01",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-yc-hn-49313047",
    "source": "Y Combinator",
    "atsType": "ycombinator",
    "collectorId": "c_mt4s1dwc1n61l4s9i4",
    "company": "Voltair (YC W26)",
    "batch": "YC Batch",
    "title": "a Test Flight Engineer",
    "location": "San Francisco, CA / Remote",
    "salaryRange": "$160,000 - $240,000",
    "equity": "0.5% - 2.0%",
    "techStack": [
      "Python",
      "TypeScript",
      "React",
      "FastAPI",
      "AI/LLM"
    ],
    "description": "YC Startup role: Voltair (YC W26) Is Hiring a Test Flight Engineer. Live scraped via Bright Data Scraper Studio Collector c_mt4s1dwc1n61l4s9i4.",
    "applyUrl": "https://www.ycombinator.com/companies/voltair/jobs/sSOD2Ox-flight-test-engineer",
    "postedDate": "2026-08-15",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-yc-hn-49171650",
    "source": "Y Combinator",
    "atsType": "ycombinator",
    "collectorId": "c_mt4s1dwc1n61l4s9i4",
    "company": "Truemetrics (YC S23)",
    "batch": "YC Batch",
    "title": "in Berlin – GTM Lead",
    "location": "San Francisco, CA / Remote",
    "salaryRange": "$160,000 - $240,000",
    "equity": "0.5% - 2.0%",
    "techStack": [
      "Python",
      "TypeScript",
      "React",
      "FastAPI",
      "AI/LLM"
    ],
    "description": "YC Startup role: Truemetrics (YC S23) Is Hiring in Berlin – GTM Lead. Live scraped via Bright Data Scraper Studio Collector c_mt4s1dwc1n61l4s9i4.",
    "applyUrl": "https://www.ycombinator.com/companies/truemetrics/jobs/bIQQ7tP-founding-gtm-lead",
    "postedDate": "2026-08-04",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-yc-hn-49377248",
    "source": "Y Combinator",
    "atsType": "ycombinator",
    "collectorId": "c_mt4s1dwc1n61l4s9i4",
    "company": "Sixtyfour (YC P25)",
    "batch": "YC Batch",
    "title": "Sixtyfour (YC P25) Is Hiring",
    "location": "San Francisco, CA / Remote",
    "salaryRange": "$160,000 - $240,000",
    "equity": "0.5% - 2.0%",
    "techStack": [
      "Python",
      "TypeScript",
      "React",
      "FastAPI",
      "AI/LLM"
    ],
    "description": "YC Startup role: Sixtyfour (YC P25) Is Hiring. Live scraped via Bright Data Scraper Studio Collector c_mt4s1dwc1n61l4s9i4.",
    "applyUrl": "https://www.ycombinator.com/companies/sixtyfour/jobs/39SkSrA-software-engineering-intern",
    "postedDate": "2026-08-20",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-yc-hn-49373423",
    "source": "Y Combinator",
    "atsType": "ycombinator",
    "collectorId": "c_mt4s1dwc1n61l4s9i4",
    "company": "Proof of Human (YC S23)",
    "batch": "YC Batch",
    "title": "a Member of Technical Staff",
    "location": "San Francisco, CA / Remote",
    "salaryRange": "$160,000 - $240,000",
    "equity": "0.5% - 2.0%",
    "techStack": [
      "Python",
      "TypeScript",
      "React",
      "FastAPI",
      "AI/LLM"
    ],
    "description": "YC Startup role: Proof of Human (YC S23) Is Hiring a Member of Technical Staff. Live scraped via Bright Data Scraper Studio Collector c_mt4s1dwc1n61l4s9i4.",
    "applyUrl": "https://www.ycombinator.com/companies/proof-of-human/jobs/ZTZHEbb-member-of-technical-staff",
    "postedDate": "2026-08-20",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-scaleai-4715970005",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Scale AI",
    "batch": "Scaleup",
    "title": "AI Advisory Consultant",
    "location": "San Francisco, CA; New York, NY",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Scale AI. Live scraped from official Greenhouse board.",
    "applyUrl": "https://job-boards.greenhouse.io/scaleai/jobs/4715970005",
    "postedDate": "2026-08-04",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-scaleai-4715976005",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Scale AI",
    "batch": "Scaleup",
    "title": "AI Advisory Principal",
    "location": "San Francisco, CA; New York, NY",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Scale AI. Live scraped from official Greenhouse board.",
    "applyUrl": "https://job-boards.greenhouse.io/scaleai/jobs/4715976005",
    "postedDate": "2026-08-04",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-scaleai-4654510005",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Scale AI",
    "batch": "Scaleup",
    "title": "AI Applications Ops Manager, GPS",
    "location": "Doha, Qatar ",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Scale AI. Live scraped from official Greenhouse board.",
    "applyUrl": "https://job-boards.greenhouse.io/scaleai/jobs/4654510005",
    "postedDate": "2026-08-19",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-scaleai-4703343005",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Scale AI",
    "batch": "Scaleup",
    "title": "AI Builder Intern",
    "location": "San Francisco, CA",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Scale AI. Live scraped from official Greenhouse board.",
    "applyUrl": "https://job-boards.greenhouse.io/scaleai/jobs/4703343005",
    "postedDate": "2026-08-11",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-scaleai-4520320005",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Scale AI",
    "batch": "Scaleup",
    "title": "AI Infrastructure Engineer, Model Serving Platform",
    "location": "San Francisco, CA; New York, NY",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Scale AI. Live scraped from official Greenhouse board.",
    "applyUrl": "https://job-boards.greenhouse.io/scaleai/jobs/4520320005",
    "postedDate": "2026-08-13",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-scaleai-4716453005",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Scale AI",
    "batch": "Scaleup",
    "title": "AI Infrastructure Engineer, Sandbox Platform",
    "location": "San Francisco, CA; Seattle, WA; New York, NY",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Scale AI. Live scraped from official Greenhouse board.",
    "applyUrl": "https://job-boards.greenhouse.io/scaleai/jobs/4716453005",
    "postedDate": "2026-08-17",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-discord-8599937002",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Discord",
    "batch": "Scaleup",
    "title": "Account Manager, Advertising Solutions",
    "location": "San Francisco Bay Area ",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Discord. Live scraped from official Greenhouse board.",
    "applyUrl": "https://job-boards.greenhouse.io/discord/jobs/8599937002",
    "postedDate": "2026-08-06",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-discord-8686353002",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Discord",
    "batch": "Scaleup",
    "title": "Advertising Operations Manager",
    "location": "San Francisco Bay Area or New York (Remote)",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Discord. Live scraped from official Greenhouse board.",
    "applyUrl": "https://job-boards.greenhouse.io/discord/jobs/8686353002",
    "postedDate": "2026-08-21",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-discord-8625545002",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Discord",
    "batch": "Scaleup",
    "title": "Associate Product Counsel, Safety",
    "location": "San Francisco Bay Area",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Discord. Live scraped from official Greenhouse board.",
    "applyUrl": "https://job-boards.greenhouse.io/discord/jobs/8625545002",
    "postedDate": "2026-07-31",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-discord-8680047002",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Discord",
    "batch": "Scaleup",
    "title": "Commercial Policy Lead, Brand Safety & Malware",
    "location": "San Francisco Bay Area ",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Discord. Live scraped from official Greenhouse board.",
    "applyUrl": "https://job-boards.greenhouse.io/discord/jobs/8680047002",
    "postedDate": "2026-08-05",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-discord-8571766002",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Discord",
    "batch": "Scaleup",
    "title": "Director of Engineering, Safety",
    "location": "San Francisco Bay Area",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Discord. Live scraped from official Greenhouse board.",
    "applyUrl": "https://job-boards.greenhouse.io/discord/jobs/8571766002",
    "postedDate": "2026-07-31",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-gh-discord-8722538002",
    "source": "Greenhouse",
    "atsType": "greenhouse",
    "collectorId": "c_gh_portal_4e1",
    "company": "Discord",
    "batch": "Scaleup",
    "title": "Engineering Manager, Machine Learning (Safety)",
    "location": "San Francisco Bay Area",
    "salaryRange": "$180,000 - $260,000",
    "equity": "Competitive Equity",
    "techStack": [
      "Python",
      "Distributed Systems",
      "Go",
      "React",
      "AWS"
    ],
    "description": "Building state of the art platforms at Discord. Live scraped from official Greenhouse board.",
    "applyUrl": "https://job-boards.greenhouse.io/discord/jobs/8722538002",
    "postedDate": "2026-08-20",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-cohere-cd3eacfe-1169-4df0-8164-93a857d5ddf0",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Cohere",
    "batch": "Series A/B",
    "title": "Revenue Operations Analyst (Analytics)",
    "location": "New York",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Cohere to build state of the art systems in Business Operations. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/cohere/cd3eacfe-1169-4df0-8164-93a857d5ddf0",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-cohere-3136a5a5-06fd-4c82-8b72-a43467e6b128",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Cohere",
    "batch": "Series A/B",
    "title": "Member of Technical Staff, Modeling",
    "location": "London",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Cohere to build state of the art systems in Modeling. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/cohere/3136a5a5-06fd-4c82-8b72-a43467e6b128",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-cohere-0183bddd-f845-4e7e-af69-e6178cdc32be",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Cohere",
    "batch": "Series A/B",
    "title": "Senior HR Business Partner",
    "location": "New York",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Cohere to build state of the art systems in People. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/cohere/0183bddd-f845-4e7e-af69-e6178cdc32be",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-cohere-443368a3-6276-4b90-9671-27fed40fd6d2",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Cohere",
    "batch": "Series A/B",
    "title": "Senior Member of Technical Staff, Multimodal AI",
    "location": "San Francisco",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Cohere to build state of the art systems in Modeling. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/cohere/443368a3-6276-4b90-9671-27fed40fd6d2",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-cohere-acec6038-117b-400b-92e3-0745fbb4cf53",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Cohere",
    "batch": "Series A/B",
    "title": "Data Annotation Specialist - German Writer/Translator",
    "location": "Canada",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Cohere to build state of the art systems in Data Quality (Contract). Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/cohere/acec6038-117b-400b-92e3-0745fbb4cf53",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  },
  {
    "id": "live-ashby-cohere-d42f5fd4-1ffc-45b9-957c-f09862db6af6",
    "source": "Ashby ATS",
    "atsType": "ashby",
    "collectorId": "c_ashby_portal_8f2",
    "company": "Cohere",
    "batch": "Series A/B",
    "title": "Member of Technical Staff, Training Performance Engineer",
    "location": "London",
    "salaryRange": "$170,000 - $240,000",
    "equity": "0.15% - 0.75%",
    "techStack": [
      "TypeScript",
      "Python",
      "React",
      "AI/LLM",
      "Rust"
    ],
    "description": "Join Cohere to build state of the art systems in Modeling. Live scraped from official Ashby portal.",
    "applyUrl": "https://jobs.ashbyhq.com/cohere/d42f5fd4-1ffc-45b9-957c-f09862db6af6",
    "postedDate": "2026-08-23",
    "healthStatus": "live_verified"
  }
];
